version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: noticias
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    volumes:
      - /media/leonardo/data_disk/postgres-data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/noticias
    depends_on:
      - db
    command: >
      sh -c "npm install && npm test && npx ts-node-dev --respawn src/index.ts"
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
